### PR TITLE
ModelValidation class implementation with example

### PR DESCRIPTION
**Pull request by ChrisJFarr**
Implementation of the ModelValidation class

Testing: See /chris_farr for model_validation_example.ipynb and try to run on local computer.

### CODE REVIEW

**Review by krisroopa — COMMENTED** [review]
Class implementation looks good to me. I do have a couple of questions.
Could we also add  Classification Report in addition to confusion matrix for classification models? 
We are also looking at dimensionality reduction techniques like PCA and T-Sne. Would those be a part of this implementation or a separate class to only understand the structure of the data.

**Comment by ChrisJFarr** [comment]
Yes I can add that. As for PCA and T-Sne, those would both be part of the preprocessing step so I didn’t include it in this implementation. You should be able to transform the data with those techniques and pass it through this module. I’ll make the update this week before merging. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChrisJFarr** [comment]
Were you able to get it running on your computer?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krisroopa** [comment]
Yeah I was able to run the code with no problem.

**Comment by kate-young** [comment]
This looks great! My only concern is with the assert statement that validates the 47 training samples. This will cause issues if we decide to try running our models on synthetic data. We may also want to use this for future projects, and it seems pretty generic otherwise. Can we remove this line? Otherwise it worked pretty well. I think this is a great way to keep all our work in a standard format.

**Comment by ChrisJFarr** [comment]
Thanks Kate, yes we can remove the 47 training samples assertion line, good point on reusing it. We can just check for this in the peer-reviews to make sure that we are all using the same starting points (47 examples in this case so the evaluation is consistent). To your point on the synthetic data, I've been brainstorming how to include a re-sampling parameter and think we can use compatibility with the imbalance-learn . That way it still keeps the test splits pure and doesn't include a related example in the train and test split. I'll make the change and recommit. If you could approve after that would be great, thanks!

**Review by kate-young — APPROVED** [review]
Looks good!

**Pull request merged**
